/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GajiKaryawan;
import Pengembalian.Pengembalian;
import KoneksiDB.KoneksiDB;
import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author abiba
 */
public class GajiKaryawan extends javax.swing.JFrame {

    KoneksiDB KoneksiDB = new KoneksiDB();

    /**
     * Creates new form GajiKaryawan
     */
    public GajiKaryawan() { //Ini Konstruktor
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Waktu();
        generatePendapatanHarian();
        generatePendapatanBulanan();
        generateGajiBulanan();
    }

    public void Waktu() {

        Thread p = new Thread() {
            public void run() {
                for (;;) {

                    Calendar kal = new GregorianCalendar();
                    int hari = kal.get(Calendar.DAY_OF_MONTH);
                    int bulan = kal.get(Calendar.MONTH) + 1;
                    int tahun = kal.get(Calendar.YEAR);
                    String tanggal = hari + "/" + bulan + "/" + tahun;
                    jLabelTanggal.setText(tanggal);
                    try {
                        sleep(1000);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        };
        p.start();
    }

    public void generatePendapatanHarian() {
        ResultSet rs = KoneksiDB.ambilData("SELECT * FROM Pengembalian GROUP BY Tanggal");
        try {
            while (rs.next()) {
                jComboHarian.addItem(rs.getString("Tanggal"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void generatePendapatanBulanan() {
        ResultSet rs = KoneksiDB.ambilData("SELECT MONTH(Tanggal) AS Bulan, YEAR(Tanggal) AS Tahun, SUM(Harga) AS TotalPendapatan FROM Pengembalian GROUP BY MONTH(Tanggal), YEAR(Tanggal) ORDER BY Tahun, Bulan");
        try {
            jComboBulanan.removeAllItems(); // Clear the combo box
            while (rs.next()) {
                int bulan = rs.getInt("Bulan");
                jComboBulanan.addItem(String.valueOf(bulan));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void generateGajiBulanan() {
        ResultSet rs = KoneksiDB.ambilData("SELECT COUNT(Tanggal) AS hehe, MONTH(Tanggal) AS Bulan, SUM(Harga) AS hoho FROM Pengembalian GROUP BY MONTH(Tanggal)");
        try {
            while (rs.next()) {
                jComboGajiBulanan.addItem(rs.getString("Bulan"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboHarian = new javax.swing.JComboBox<>();
        jCetak1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPendapatan1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCetak2 = new javax.swing.JButton();
        jPendapatanBulanan = new javax.swing.JTextField();
        jComboBulanan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboGajiBulanan = new javax.swing.JComboBox<>();
        jKaryawan = new javax.swing.JTextField();
        jCetak3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1920, 121));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectUAS2/sibhp3.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gaji Karyawan dan Laporan Keuangan");

        jLabelTanggal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTanggal.setText("jLabel3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(515, 515, 515)
                .addComponent(jLabelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel3.setText("Laporan Pendapatan Harian");

        jComboHarian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboHarian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH TANGGAL --" }));
        jComboHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboHarianActionPerformed(evt);
            }
        });

        jCetak1.setBackground(new java.awt.Color(51, 51, 51));
        jCetak1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jCetak1.setForeground(new java.awt.Color(255, 255, 255));
        jCetak1.setText("Cetak");
        jCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCetak1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel6.setText("Pilih Tanggal :");

        jPendapatan1.setEditable(false);
        jPendapatan1.setBackground(new java.awt.Color(204, 204, 204));
        jPendapatan1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jPendapatan1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPendapatan1.setBorder(null);
        jPendapatan1.setFocusable(false);
        jPendapatan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPendapatan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jCetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(jPendapatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboHarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jPendapatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel7.setText("Laporan Pendapatan Bulanan");

        jCetak2.setBackground(new java.awt.Color(51, 51, 51));
        jCetak2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jCetak2.setForeground(new java.awt.Color(255, 255, 255));
        jCetak2.setText("Cetak");
        jCetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCetak2ActionPerformed(evt);
            }
        });

        jPendapatanBulanan.setEditable(false);
        jPendapatanBulanan.setBackground(new java.awt.Color(204, 204, 204));
        jPendapatanBulanan.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jPendapatanBulanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPendapatanBulanan.setBorder(null);
        jPendapatanBulanan.setFocusable(false);
        jPendapatanBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPendapatanBulananActionPerformed(evt);
            }
        });

        jComboBulanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBulanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH BULAN --" }));
        jComboBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBulananActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel8.setText("Pilih Bulan :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jPendapatanBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(58, 58, 58)
                .addComponent(jPendapatanBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel5.setText("Gaji Karyawan");

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel4.setText("Pilih Bulan :");

        jComboGajiBulanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboGajiBulanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH Bulan --" }));
        jComboGajiBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGajiBulananActionPerformed(evt);
            }
        });

        jKaryawan.setEditable(false);
        jKaryawan.setBackground(new java.awt.Color(204, 204, 204));
        jKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jKaryawan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jKaryawan.setBorder(null);
        jKaryawan.setFocusable(false);
        jKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKaryawanActionPerformed(evt);
            }
        });

        jCetak3.setBackground(new java.awt.Color(51, 51, 51));
        jCetak3.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jCetak3.setForeground(new java.awt.Color(255, 255, 255));
        jCetak3.setText("Cetak");
        jCetak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCetak3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboGajiBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jCetak3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(141, 141, 141))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboGajiBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jCetak3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1931, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboHarianActionPerformed
        // TODO add your handling code here:
        if (jComboHarian.getSelectedItem() != "--Pilih Tanggal--") {
            ResultSet rs = KoneksiDB.ambilData("SELECT COUNT(Tanggal) AS hehe, Tanggal, SUM(Harga) AS hoho FROM Pengembalian WHERE Tanggal = '" + jComboHarian.getSelectedItem() + "' GROUP BY Tanggal");
            try {
                if (rs.next()) {
                    jPendapatan1.setText(rs.getString("hoho"));
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboHarianActionPerformed

    private void jKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKaryawanActionPerformed

    private void jComboGajiBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGajiBulananActionPerformed
        // TODO add your handling code here:
        if (jComboGajiBulanan.getSelectedItem() != "--Pilih Bulan--") {
            ResultSet rs = KoneksiDB.ambilData("SELECT COUNT(Tanggal) AS hehe, MONTH(Tanggal) AS Bulan, SUM(Harga) AS hoho FROM Pengembalian WHERE MONTH(Tanggal) = MONTH('" + jComboGajiBulanan.getSelectedItem() + "') GROUP BY MONTH(Tanggal)");
            try {
                if (rs.next()) {
                    int jumlahHari = rs.getInt("hehe");
                    int totalPendapatan = jumlahHari * 20000;
                    jKaryawan.setText(String.valueOf(totalPendapatan));
                } else {
                    String totalPendapatan = "600000";
                    jKaryawan.setText(totalPendapatan); // Nilai default jika tidak ada total pendapatan
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboGajiBulananActionPerformed

    private void jPendapatan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPendapatan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPendapatan1ActionPerformed

    private void jPendapatanBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPendapatanBulananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPendapatanBulananActionPerformed

    private void jComboBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBulananActionPerformed
        // TODO add your handling code here:
        ResultSet rs = KoneksiDB.ambilData("SELECT MONTH(Tanggal) AS Bulan, YEAR(Tanggal) AS Tahun, SUM(Harga) AS TotalPendapatan FROM Pengembalian GROUP BY MONTH(Tanggal), YEAR(Tanggal) ORDER BY Tahun, Bulan");
        try {
            jComboBulanan.removeAllItems(); // Clear the combo box
            jComboBulanan.addItem("-- Pilih Bulan --"); // Add the default "-- Pilih Bulan --" item
            while (rs.next()) {
                int bulan = rs.getInt("Bulan");
                int tahun = rs.getInt("Tahun");
                int totalPendapatan = rs.getInt("TotalPendapatan");
                jComboBulanan.addItem(String.valueOf(bulan));

                // Add a listener to the combo box
                jComboBulanan.addActionListener(e -> {
                    int selectedMonth = jComboBulanan.getSelectedIndex() > 0 ? Integer.parseInt((String) jComboBulanan.getSelectedItem()) : 0;
                    if (selectedMonth == bulan) {
                        jPendapatanBulanan.setText(String.valueOf(totalPendapatan));
                    } else if (selectedMonth == 0) {
                        jPendapatanBulanan.setText(""); // Clear the JTextField if "-- Pilih Bulan --" is selected
                    }
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBulananActionPerformed

    private void jCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCetak1ActionPerformed
        // TODO add your handling code here:
        try {
            File f = new File("src/Report/ReportPendapatanHarian.jasper");
            //String file = "D:\\netbeans document\\ProjectUAS2\\src\\ReportGaji\\ReportHarian.jrxml";
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructors();
            HashMap<String, Object> param = new HashMap<>();
            param.put("TotalPendapan", jComboHarian.getSelectedItem());
            param.put("TotalTransaksi", jComboHarian.getSelectedItem());
            param.put("Tanggal", jComboHarian.getSelectedItem());
            KoneksiDB.koneksi();
            JasperPrint print = JasperFillManager.fillReport(f.getAbsolutePath(), param, KoneksiDB.con);
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jCetak1ActionPerformed

    private void jCetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCetak2ActionPerformed
        // TODO add your handling code here:
         try {
            File f = new File("src/Report/ReportPendapatanBulanan.jasper");
            //String file = "D:\\netbeans document\\ProjectUAS2\\src\\ReportGaji\\ReportHarian.jrxml";
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructors();
            HashMap<String, Object> param = new HashMap<>();
            param.put("Bulan", jComboBulanan.getSelectedItem());
            param.put("Tahun", jComboBulanan.getSelectedItem());
            param.put("TotalPendapatan", jComboBulanan.getSelectedItem());
            KoneksiDB.koneksi();
            JasperPrint print = JasperFillManager.fillReport(f.getAbsolutePath(), param, KoneksiDB.con);
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jCetak2ActionPerformed

    private void jCetak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCetak3ActionPerformed
        // TODO add your handling code here:
         try {
            File f = new File("src/Report/ReportGajiBulanan.jasper");
            //String file = "D:\\netbeans document\\ProjectUAS2\\src\\ReportGaji\\ReportHarian.jrxml";
            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructors();
            HashMap<String, Object> param = new HashMap<>();
            param.put("Bulan", jComboGajiBulanan.getSelectedItem());
            KoneksiDB.koneksi();
            JasperPrint print = JasperFillManager.fillReport(f.getAbsolutePath(), param, KoneksiDB.con);
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jCetak3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pengembalian Pengembalian = new Pengembalian();
        Pengembalian.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCetak1;
    private javax.swing.JButton jCetak2;
    private javax.swing.JButton jCetak3;
    private javax.swing.JComboBox<String> jComboBulanan;
    private javax.swing.JComboBox<String> jComboGajiBulanan;
    private javax.swing.JComboBox<String> jComboHarian;
    private javax.swing.JTextField jKaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jPendapatan1;
    private javax.swing.JTextField jPendapatanBulanan;
    // End of variables declaration//GEN-END:variables
}
